// File: single_port_ram.v
// Generated by MyHDL 0.11
// Date: Tue Jun  9 17:31:45 2020


`timescale 1ns/10ps

module single_port_ram (
    clk,
    we,
    addr,
    din,
    dout
);


input clk;
input we;
input [15:0] addr;
input [15:0] din;
output [15:0] dout;
wire [15:0] dout;

reg [15:0] ram_single_port [0:16-1];

initial begin: INITIALIZE_RAM_SINGLE_PORT
    integer i;
    for(i=0; i<16; i=i+1) begin
        ram_single_port[i] = 0;
    end
end



// write data to address 'addr' 
always @(posedge clk) begin: SINGLE_PORT_RAM_WRITE_LOGIC
    if ((we == 1)) begin
        ram_single_port[addr] <= din;
    end
end

// read data from address 'addr' 

assign dout = ram_single_port[addr];

endmodule
