// File: test.v
// Generated by MyHDL 0.11
// Date: Tue Jun  9 16:32:08 2020


`timescale 1ns/10ps

module test (
    selector
);


input [8:0] selector;

wire [15:0] CPC;
wire [15:0] TVEC0;
wire [15:0] TVEC1;
wire [15:0] TVEC2;
wire [15:0] TVEC3;
wire [15:0] EPC;
wire GIE;
wire PGIE;
wire IE0;
wire IE1;
wire IE2;
wire IE3;
reg [15:0] tvec;
wire int0_acc;
wire int1_acc;
wire int2_acc;

assign CPC = 16'd0;
assign TVEC0 = 16'd0;
assign TVEC1 = 16'd0;
assign TVEC2 = 16'd0;
assign TVEC3 = 16'd0;
assign EPC = 16'd0;
assign GIE = 1'd0;
assign PGIE = 1'd0;
assign IE0 = 1'd0;
assign IE1 = 1'd0;
assign IE2 = 1'd0;
assign IE3 = 1'd0;
assign int0_acc = 1'd0;
assign int1_acc = 1'd0;
assign int2_acc = 1'd0;


always @(IE1, CPC, PGIE, IE0, TVEC0, TVEC1, TVEC2, GIE, IE2, TVEC3, int1_acc, selector, EPC, int0_acc, int2_acc, IE3) begin: TEST_COMB_LOGIC
    reg [16-1:0] cr_data;
    if (int0_acc) begin
        tvec = TVEC0;
    end
    else if (int1_acc) begin
        tvec = TVEC1;
    end
    else if (int2_acc) begin
        tvec = TVEC2;
    end
    else begin
        tvec = TVEC3;
    end
    casez (selector)
        9'b????????1: begin
            cr_data[16-1:2] = 14'h0;
            cr_data[1] = PGIE;
            cr_data[0] = GIE;
        end
        9'b???????1?: begin
            cr_data[16-1:4] = 12'h0;
            cr_data[3] = IE3;
            cr_data[2] = IE2;
            cr_data[1] = IE1;
            cr_data[0] = IE0;
        end
        9'b??????1??: begin
            cr_data = EPC;
        end
        9'b?????1???: begin
            cr_data = CPC;
        end
        9'b???1?????: begin
            cr_data = TVEC0;
        end
        9'b??1??????: begin
            cr_data = TVEC1;
        end
        9'b?1???????: begin
            cr_data = TVEC2;
        end
        9'b1????????: begin
            cr_data = TVEC3;
        end
    endcase
end

endmodule
