// File: test2.v
// Generated by MyHDL 0.11
// Date: Tue Jun  9 17:16:22 2020


`timescale 1ns/10ps

module test2 (

);



wire [1:0] TVEC0;

assign TVEC0 = 2'd0;


always @(TVEC0) begin: TEST2_TEST2_LOGIC
    reg [2-1:0] in16;
    reg [2-1:0] out16;
    if (in16) begin
        out16 = TVEC0;
    end
end

endmodule
